###
GET http://localhost:8080/suppliers


###

DELETE http://localhost:8080/suppliers/3

###
POST http://localhost:8080/suppliers/add
content-Type: application/json

{
    "naziv":"kanban uvoznik"
}
###

POST http://localhost:8080/warehouses/add
content-Type: application/json

{
    "naziv":"skladiste elidza",
    "naziv_lokacije":"kruzni tok"
}


###

PUT http://localhost:8080/suppliers/2
content-Type: application/json

{
    "naziv":"Coca cola uvoznik"
}

###

POST http://localhost:8080/users/login 
content-Type: application/json

{
"name": "Kyle", "password": "password"
}